### ISSUE TITLE
text update

### ISSUE THREAD

**Issue by zhangzhongnan928** [alpha-wallet/alpha-wallet-website#9]
<img width="1051" alt="screen shot 2018-09-18 at 7 53 21 pm" src="https://user-images.githubusercontent.com/33795543/45686599-6d12f600-bb7f-11e8-8c7d-75c97315c6e2.png">
<img width="834" alt="screen shot 2018-09-18 at 7 54 36 pm" src="https://user-images.githubusercontent.com/33795543/45686600-6d12f600-bb7f-11e8-97df-2ac26a2753a6.png">
<img width="945" alt="screen shot 2018-09-18 at 7 54 55 pm" src="https://user-images.githubusercontent.com/33795543/45686601-6d12f600-bb7f-11e8-8358-8f970d209015.png">
<img width="484" alt="screen shot 2018-09-18 at 8 12 14 pm" src="https://user-images.githubusercontent.com/33795543/45686602-6dab8c80-bb7f-11e8-9468-676271fea62f.png">

**Comment by zhangzhongnan928** [comment]
@farrahfazirah

**Comment by zhangzhongnan928** [comment]
The updates is not in wordpress ?

**Comment by farrahfazirah** [comment]
I just uploaded the new changes onto Wordpress.

It's quite troublesome to always delete and then upload a theme. It takes quite a while so I only upload if I have done major design changes.
